export const grcConfig = {
  study: {
    attributes: [
      {
        id: "regulatory_framework",
        label: "Regulatory Coverage",
        in_byo: true,
        price_type: "none" as const,
        levels: [
          { id: "single", label: "Single framework (e.g. SOX only)" },
          { id: "few", label: "2-3 frameworks" },
          { id: "multi", label: "Multi-framework" },
          { id: "multi_ai", label: "Multi-framework incl. GDPR / DORA / EU AI Act" },
        ],
      },
      {
        id: "deployment_location",
        label: "Deployment & Data Location",
        in_byo: true,
        price_type: "none" as const,
        levels: [
          { id: "shared_no_guarantee", label: "Shared SaaS, no regional guarantee" },
          { id: "shared_major_region", label: "Shared SaaS, choice of major region (US or EU)" },
          { id: "tenant_in_region", label: "Tenant-isolated cloud, in-region hosting for your jurisdiction" },
          { id: "cmk_in_region", label: "Customer-managed keys, in-region hosting" },
          { id: "onprem_sovereign", label: "On-prem / air-gapped, dedicated in-country / sovereign instance" },
        ],
      },
      {
        id: "ai_autonomy",
        label: "AI Autonomy",
        in_byo: true,
        price_type: "none" as const,
        levels: [
          { id: "zero_ai", label: "No AI" },
          { id: "ai_suggests", label: "AI suggests, human executes" },
          { id: "ai_executes_approved", label: "AI acts, you approve before it sticks" },
          { id: "ai_auto_spot", label: "AI runs autonomously, you review exceptions" },
          { id: "fully_auto", label: "Fully autonomous" },
        ],
      },
      {
        id: "tprm",
        label: "Third-Party Risk Depth",
        in_byo: true,
        price_type: "none" as const,
        levels: [
          { id: "not_included", label: "Not included" },
          { id: "basic_vendor", label: "Basic vendor questionnaires" },
          { id: "full_tprm", label: "Full TPRM suite" },
          { id: "nth_party", label: "Nth-party + supply chain inventory" },
        ],
      },
      {
        id: "connected_risk",
        label: "Connected-Risk Data Foundation",
        in_byo: true,
        price_type: "none" as const,
        levels: [
          { id: "siloed", label: "Siloed modules (each area keeps its own data)" },
          { id: "shared_inventory", label: "Shared inventory of core objects across modules" },
          { id: "unified_core", label: "Unified data core (one system of record)" },
          { id: "write_back", label: "Connected write-back (agents act across modules)" },
        ],
      },
      {
        id: "integrations",
        label: "Integration Ecosystem",
        in_byo: true,
        price_type: "none" as const,
        levels: [
          { id: "standalone", label: "Standalone (no connectors)" },
          { id: "few_connectors", label: "A few connectors" },
          { id: "broad_ootb", label: "50+ pre-built connectors" },
          { id: "open_api", label: "Broad connector library + open API + MCP" },
        ],
      },
      {
        id: "annual_price",
        label: "Annual Platform Price",
        in_byo: false,
        price_type: "none" as const,
        levels: [
          { id: "p30_60k", label: "$30K-$60K/yr" },
          { id: "p61_150k", label: "$61K-$150K/yr" },
          { id: "p151_250k", label: "$151K-$250K/yr" },
          { id: "p251k_plus", label: "$251K+/yr" },
        ],
      },
      {
        id: "pricing_model",
        label: "Pricing Structure",
        in_byo: false,
        price_type: "none" as const,
        levels: [
          { id: "flat_annual", label: "Flat annual subscription" },
          { id: "per_seat", label: "Per-seat" },
          { id: "usage_per_control", label: "Usage-based (per control tested)" },
          { id: "hybrid_credits", label: "Hybrid: base + credits add-on" },
        ],
      },
    ],
    design: {
      T: 16,
      Amin: 2,
      Amax: 4,
      screens_per_concept_batch: 4,
      total_screening_screens: 4,
      price_variation_pct: 0,
      price_rounding: 1,
    },
    phases: {
      byo: true,
      screening: true,
      must_have: true,
      unacceptable: true,
      tournament: true,
      calibration: true,
    },
    estimation: {
      method: "mnl" as const,
      price_function: "linear" as const,
    },
  },
} as const;
