export const grcConfig = {
  study: {
    attributes: [
      {
        id: "regulatory_framework",
        label: "Regulatory Coverage",
        in_byo: true,
        price_type: "none" as const,
        levels: [
          { id: "single", label: "Single framework (e.g. SOX only)" },
          { id: "few", label: "2-3 frameworks" },
          { id: "multi", label: "Multi-framework" },
          { id: "multi_ai", label: "Multi-framework incl. GDPR / DORA / EU AI Act" },
        ],
      },
      {
        id: "deployment",
        label: "Deployment & Data Residency",
        in_byo: true,
        price_type: "none" as const,
        levels: [
          { id: "shared_saas", label: "Shared SaaS" },
          { id: "tenant_isolated", label: "Tenant-isolated cloud" },
          { id: "cmk", label: "Customer-managed keys" },
          { id: "on_prem", label: "On-prem / air-gapped" },
        ],
      },
      {
        id: "ai_autonomy",
        label: "AI Autonomy",
        in_byo: true,
        price_type: "none" as const,
        levels: [
          { id: "zero_ai", label: "No AI" },
          { id: "ai_suggests", label: "AI suggests, human executes" },
          { id: "ai_executes_approved", label: "AI acts, you approve before it sticks" },
          { id: "ai_auto_spot", label: "AI runs autonomously, you review exceptions" },
          { id: "fully_auto", label: "Fully autonomous" },
        ],
      },
      {
        id: "tprm",
        label: "Third-Party Risk Depth",
        in_byo: true,
        price_type: "none" as const,
        levels: [
          { id: "not_included", label: "Not included" },
          { id: "basic_vendor", label: "Basic vendor questionnaires" },
          { id: "full_tprm", label: "Full TPRM suite" },
          { id: "nth_party", label: "Nth-party + supply chain inventory" },
        ],
      },
      {
        id: "time_to_value",
        label: "Implementation Time-to-Value",
        in_byo: true,
        price_type: "none" as const,
        levels: [
          { id: "lt30", label: "Under 30 days" },
          { id: "30_90", label: "30-90 days" },
          { id: "90_180", label: "90-180 days" },
          { id: "gt180", label: "180+ days" },
        ],
      },
      {
        id: "integrations",
        label: "Integration Ecosystem",
        in_byo: true,
        price_type: "none" as const,
        levels: [
          { id: "standalone", label: "Standalone (no connectors)" },
          { id: "few_connectors", label: "A few connectors" },
          { id: "broad_ootb", label: "50+ pre-built connectors" },
          { id: "open_api", label: "200+ connectors + open API / MCP" },
        ],
      },
      {
        id: "annual_price",
        label: "Annual Platform Price",
        in_byo: false,
        price_type: "none" as const,
        levels: [
          { id: "p30_60k", label: "$30K-$60K/yr" },
          { id: "p61_150k", label: "$61K-$150K/yr" },
          { id: "p151_250k", label: "$151K-$250K/yr" },
          { id: "p251k_plus", label: "$251K+/yr" },
        ],
      },
      {
        id: "pricing_model",
        label: "Pricing Structure",
        in_byo: false,
        price_type: "none" as const,
        levels: [
          { id: "flat_annual", label: "Flat annual subscription" },
          { id: "per_seat", label: "Per-seat" },
          { id: "usage_per_control", label: "Usage-based (per control tested)" },
          { id: "hybrid_credits", label: "Hybrid: base + credits add-on" },
        ],
      },
    ],
    design: {
      T: 16,
      Amin: 2,
      Amax: 4,
      screens_per_concept_batch: 4,
      total_screening_screens: 4,
      price_variation_pct: 0,
      price_rounding: 1,
    },
    phases: {
      byo: true,
      screening: true,
      must_have: true,
      unacceptable: true,
      tournament: true,
      calibration: true,
    },
    estimation: {
      method: "mnl" as const,
      price_function: "linear" as const,
    },
  },
} as const;
